### ISSUE TITLE
Demo app is not working

### ISSUE THREAD

**Issue by SagiMedina** [OmriGM/wink-browser-controller#1]
Getting "Application error" from heroku 
![image](https://user-images.githubusercontent.com/6016435/147675743-182cb190-f1d1-4c78-84eb-10bdaf0b7f30.png)

**Comment by OmriGM** [comment]
This was the problem we had:
https://stackoverflow.com/questions/59205530/heroku-server-crashes-with-javascript-heap-out-of-memory-when-deploying-react

Thanks for reporting @SagiMedina
